### ISSUE TITLE
Failed to execute 'createElement' on 'Document

### ISSUE THREAD

**Issue by jahnvi-rtsvrf** [trycourier/courier-react#493]
Hi courier team,

I am using @trycourier/react-inbox and @trycourier/react-provider to show notifications. I am constantly getting error with rendering the inbox. It used to work fine until 9 Aug, 2023. Suddenly it started complaining after I installed them again in my repository.

It says `Failed to execute 'createElement' on 'Document': The tag name provided ('/static/media/index.03c051b94ee5090ce746.cjs') is not a valid name.`

You can take a look at my code here. I have also attached a screenshot of error below.

```
import React from "react";
import { CourierProvider } from "@trycourier/react-provider";
import { Inbox } from "@trycourier/react-inbox";
const AvInbox = ({ userId }) => {
  return (
    <div className="w-full my-4">
      {userId &&  (
        <CourierProvider
          userId={userId}
          clientKey={process.env.REACT_APP_COURIER_CLIENT_KEY}
        >
          <Inbox isOpen={true} defaultIcon={false} title="AV Inbox" />
        </CourierProvider>
      )}
    </div>

```
<img width="1349" alt="Screenshot 2023-08-10 at 3 02 44 PM" src="https://github.com/trycourier/courier-react/assets/130337632/7edd3b88-a5eb-4913-91a4-a06a9a260625">

**Comment by crrojas88** [comment]
For context, it looks like we use a package markdown-to-jsx and our dependency is 7.1.7 and if you have 7.3 installed it breaks. Downgrading to 7.1.X will fix the issue.

**Comment by rileylnapier** [comment]
i think this was resolved right?  closing out, please reopen if we need to look at it again
