### ISSUE TITLE
Create a domain for browser sdks to make it easier for CSP headers

### ISSUE THREAD

**Issue by wjureczka** [trycourier/courier-react#511]
Hello there!
Thank you for your work! I am writing to you with a specific problem. Currently, we use `courier-react` in our frontend apps. When we were working on our `Content Security Policy`, we noticed that all requests are sent to this url: `  "https://fxw3r7gdm9.execute-api.us-east-1.amazonaws.com/production";`. Do you plan to set up some of yours domains before it? Something like `https://client.courier.com/`, `https://api.courier.com/client? The AWS domain can change as far as we understand.

Cheers!

**Comment by rileylnapier** [comment]
hi, this was done we have realtime.courier.com for websockets and inbox.courier.com now.  can you upgrade and verify?
