### ISSUE TITLE
@trycourier/react-preferences Cannot find module "date-fns/format" in v5.1.0

### ISSUE THREAD

**Issue by GunnarHolwerda** [trycourier/courier-react#558]
Hey all, I recently updated to `v5.1.0` of `@trycourier/react-preferences` and started getting a `Cannot find module date-fns/format` error.

I was able to install it by installing date-fns myself, but it appears like in v5.0.0 that `date-fns/format` was imported in [format_digest.ts of react-preferences](https://github.com/trycourier/courier-react/blob/c05d7c09bf7864cfc392ca0affa98e709808f610/packages/react-preferences/src/utils/format_digest.ts#L1). But the package isn't listed as a dependency or peer dependency in the package.json. 

It looks like it's only marked as a [dependency of react-inbox](https://github.com/trycourier/courier-react/blob/c05d7c09bf7864cfc392ca0affa98e709808f610/packages/react-inbox/package.json#L28). I wonder if it got hoisted by yarn workspaces or something?

Would love to have an update so I don't have to have a secret peer dependency installed in my app 😄 I could make the update myself, but not sure if all want that dependency or not in this specific package.

**Comment by bwebs** [comment]
Good catch, was introduced with digest schedules being displayed in local time. Will get this added to react-preferences and a new release.

**Comment by GunnarHolwerda** [comment]
Thanks!

**Comment by LucasLemanowicz** [comment]
Thanks for fixing this @bwebs, is there a timeline for when v5.1.1 will be released?

**Comment by bwebs** [comment]
Thanks for the nudge, just released [5.1.1](https://github.com/trycourier/courier-react/releases/tag/v5.1.1)
