### ISSUE TITLE
Conflict in react applications due to the styled-components dependency in react-provider

### ISSUE THREAD

**Issue by kiranbose** [trycourier/courier-react#593]
We are encountering a conflict in our React applications due to the use of both Emotion and styled-components for CSS-in-JS styling. While Emotion is our preferred library for CSS preprocessing across all our 6sense apps, the <CourierProvider /> component from @trycourier/react-provider relies on styled-components (as seen in [this code](https://github.com/trycourier/courier-react/blob/main/packages/react-provider/src/index.tsx#L48-L62)). This dependency is causing runtime errors due to conflicts with Emotion.

To clarify, <CourierProvider /> is the only component we utilize from the @trycourier/react-provider package to initialize Courier in our applications. Unfortunately, the indirect dependency on styled-components in this provider is leading to CSS specificity issues and other conflicts.

To ensure compatibility and stability in our apps, we kindly request that you consider removing the styled-components dependency from `<CourierProvider />`. Doing so would allow us to safely use your provider component without encountering these conflicts. Or please provide potential solutions or updates.

**Comment by rileylnapier** [comment]
Hi, this was merged and should be released in the most recent release.
