### ISSUE TITLE
Missing documentation for how to get notified about new messages

### ISSUE THREAD

**Issue by anton-series** [trycourier/courier-react#601]
Is there any way to get notified when a new message arrives - anywhere in Inbox or hooks? 

I couldn't find it and `onEvent()` is not being called when new notifications are delivered. 

Use case: I want to send a notification via browser's Notifications API when a new notification is received, so that the user is notified instantly.

**Comment by rileylnapier** [comment]
https://github.com/trycourier/courier-react/tree/main/packages/react-provider#listening-to-messsages
